export const LevelDataActionTypes = {
    UPDATE_PROGRESS_POINTS: "UPDATE_PROGRESS_POINTS",
    UPDATE_PROGRESS_PERCENT: "UPDATE_PROGRESS_PERCENT",
    UPDATE_EARNED_POINTS: 'UPDATE_EARNED_POINTS',
    UPDATE_EARNED_PERCENT: "UPDATE_EARNED_PERCENT",
    UPDATE_LEVEL: "UPDATE_LEVEL",

}