export const GoalsActionTypes = {
    ADD_GOAL: 'ADD_GOAL',
    REMOVE_GOAL: 'REMOVE_GOAL',
    CHECK_GOAL: 'CHECK_GOAL',
    COMPLETE_GOALS: 'COMPLETE_GOALS',
    COMPLETE_GOALS_TEST: 'COMPLETE_GOALS_TEST',
    RESET_EARNED_POINTS: 'RESET_EARNED_POINTS',
};