export const GameDataActionTypes = {
    UPDATE_PROGRESS_POINTS: 'UPDATE_PROGRESS_POINTS',
    UPDATE_PROGRESS_PERCENT: 'UPDATE_PROGRESS_PERCENT',
    UPDATE_EARNED_POINTS: 'UPDATE_EARNED_POINTS',
    UPDATE_EARNED_PERCENT: "UPDATE_EARNED_PERCENT",
    UPDATE_LEVEL: 'UPDATE_LEVEL',
    CALC_POINTS_TO_LEVEL: 'CALC_POINTS_TO_LEVEL',
    ADD_GOAL: 'ADD_GOAL',
    REMOVE_GOAL: 'REMOVE_GOAL',
    CHECK_GOAL: 'CHECK_GOAL',
    COMPLETE_GOALS: 'COMPLETE_GOALS',
    COMPLETE_GOALS_TEST: 'COMPLETE_GOALS_TEST',
    RESET_EARNED_POINTS: 'RESET_EARNED_POINTS',
    COUNT_GOALS: 'COUNT_GOALS,',
    TOGGLE_REWARD_POPUP: 'TOGGLE_REWARD_POPUP',
    ADD_REWARD: 'ADD_REWARD',

}