export const MenuActionTypes = {
    TOGGLE_MENU: 'TOGGLE_MENU',
    TOGGLE_MENU_POPUP: 'TOGGLE_MENU_POPUP',
    TOGGLE_TODO_LIST: 'TOGGLE_TODO_LIST',
    TOGGLE_DAILY_LIST: 'TOGGLE_DAILY_LIST',
    TOGGLE_WEEKLY_LIST: 'TOGGLE_WEEKLY_LIST',
    TOGGLE_MONTHLY_LIST: 'TOGGLE_MONTHLY_LIST',
    TOGGLE_MENU_POPUP: 'TOGGLE_MENU_POPUP',
    MENU_SELECTION: 'MENU_SELECTION',
    MENU_ACCEPT: 'MENU_ACCEPT',
};